server:
  port: 8763
  servlet:
    context-path: /eurekaclient8763

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eurekaserver/eureka/ #eureka注册中心地址
      
spring:
  application:
    name: eurekaclient8763  #在注册中心显示的名字