server:
  port: 9710
    
spring:
  application:
    name: consumer9710  #在注册中心显示的名字
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eurekaserver/eureka/ #eureka注册中心地址