server:
  port: 8780

spring:
  application:
    name: ribbon8780  #在注册中心显示的名字

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eurekaserver/eureka/ #eureka注册中心地址