server:
  port: 9700
  
spring:
  application:
    name: provider9700  #在注册中心显示的名字
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eurekaserver/eureka/ #eureka注册中心地址